package io.github.bananamod.entity.animation;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;


public class ModAnimations {
	public static final Animation IDLE = Animation.Builder.create(4f)
			.addBoneAnimation("torso",
				new Transformation(Transformation.Targets.TRANSLATE, 
					new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(2.375f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("chest",
				new Transformation(Transformation.Targets.TRANSLATE, 
					new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(2.375f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("chest",
				new Transformation(Transformation.Targets.SCALE,
					new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2.375f, AnimationHelper.createScalingVector(1f, 1.1f, 1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(4f, AnimationHelper.createScalingVector(1f, 1f, 1f),
						Transformation.Interpolations.LINEAR))).build();
			public static final Animation POUND = Animation.Builder.create(2f).looping()
			.addBoneAnimation("body",
				new Transformation(Transformation.Targets.TRANSLATE, 
					new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("body",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5f, AnimationHelper.createRotationalVector(-57.5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5416766f, AnimationHelper.createRotationalVector(-57.5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.7916766f, AnimationHelper.createRotationalVector(-56.87f, 10.52f, 6.79f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.9583434f, AnimationHelper.createRotationalVector(-57.27f, -4.58f, -2.94f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.1676667f, AnimationHelper.createRotationalVector(-56.89f, 9.5f, 6.14f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5f, AnimationHelper.createRotationalVector(-57.5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("front_right_leg",
				new Transformation(Transformation.Targets.TRANSLATE, 
					new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("front_right_leg",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, -30f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("front_left_leg",
				new Transformation(Transformation.Targets.TRANSLATE, 
					new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("front_left_leg",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5416766f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 47.5f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 47.5f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
				new Transformation(Transformation.Targets.TRANSLATE, 
					new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -6f, -3f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, -6f, -3f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5f, AnimationHelper.createRotationalVector(57.5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5f, AnimationHelper.createRotationalVector(57.5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("front_left_hand",
				new Transformation(Transformation.Targets.TRANSLATE, 
					new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("front_left_hand",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("front_right_hand",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 90f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("front_left_arm",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("front_right_arm",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR))).build();
			public static final Animation ATTACK = Animation.Builder.create(1f).looping()
			.addBoneAnimation("body",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4583433f, AnimationHelper.createRotationalVector(-47.5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
				new Transformation(Transformation.Targets.TRANSLATE, 
					new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, -5f, -3f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, -5f, -3f),
						Transformation.Interpolations.LINEAR), 
					new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(50f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5834334f, AnimationHelper.createRotationalVector(50f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("front_right_leg",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5f, AnimationHelper.createRotationalVector(-55f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.7083434f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("front_left_leg",
				new Transformation(Transformation.Targets.ROTATE,
					new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5f, AnimationHelper.createRotationalVector(-42.5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR))).build();
			public static final Animation WALK = Animation.Builder.create(0f).build();

}
